# 3_global_affine.py
import argparse
import os
import geopandas as gpd
import numpy as np
from shapely.geometry import Polygon
import PlotMap

class PiecewiseControlWarpPipeline:
    def __init__(self, result_dir="RESULT", weight=10000.0, show_pairs=False):
        self.result_dir = result_dir
        self.input_gpkg = os.path.abspath(os.path.join(result_dir, "02_parcel_conflation_aligned.gpkg"))
        self.output_gpkg = os.path.abspath(os.path.join(result_dir, "03_global_aligned.gpkg"))
        self.vertex_col = "Vertex_Sequenc"
        self.control_targets = {}
        self.fix_control_weight = weight
        self.show_pairs = show_pairs

    def run_transform_pipeline(self):
        print("\n" + "="*60)
        print("  STEP 3: GLOBAL WEIGHTED AFFINE WARP REGRESSION ENGINE")
        print(f"  [CONFIGURATION] Fix Control Variable Weight: {self.fix_control_weight}")
        print(f"  [CONFIGURATION] Verbose Node Pairing Table: {self.show_pairs}")
        print("="*60)

        print(f"[DATABASE IO] Opening input alignment workspace:\n  -> Path: {self.input_gpkg}")
        self.gdf_all = gpd.read_file(self.input_gpkg, layer="aligned_parcels")
        
        # Load the clean point layer generated by Step 2
        try:
            gdf_adj_vertices = gpd.read_file(self.input_gpkg, layer="adjusted_vertices")
            print(f"[DATABASE IO] Opened adjusted vertices layer tracking {len(gdf_adj_vertices)} node locations.")
        except Exception:
            raise FileNotFoundError(f"[ERROR] Required 'adjusted_vertices' layer missing from {self.input_gpkg}!")

        try:
            self.gdf_fix = gpd.read_file(self.input_gpkg, layer="fix_control")
            print(f"[DATABASE IO] Isolated FIX_CONTROL layer tracking {len(self.gdf_fix)} absolute anchor points.")
        except Exception:
            self.gdf_fix = None
            print("[DATABASE IO] Warning: fix_control layer not detected in database.")

        # Build lookups for the L1 framework boundary shapes (Priority 1 Target)
        l1_targets = {}
        gdf_l1 = self.gdf_all[self.gdf_all['Class'] == 'L1']
        for idx, row in gdf_l1.iterrows():
            labels = [lbl.strip() for lbl in str(row[self.vertex_col]).split(",")][:-1]
            coords = list(row["geometry"].exterior.coords)[:-1]
            for label, coord in zip(labels, coords):
                l1_targets[label] = (float(coord[0]), float(coord[1]))

        # Map fix_control anchor coordinates strictly by string identifier matching (Priority 2 Target)
        fix_lookup = {}
        if self.gdf_fix is not None and not self.gdf_fix.empty:
            for idx, row in self.gdf_fix.iterrows():
                fix_lookup[str(row['id']).strip()] = (float(row['geometry'].x), float(row['geometry'].y))

        # Compile optimization tie-point pairs by reading the adjusted points layer
        src_pts = []
        dst_pts = []
        weights = []
        
        if self.show_pairs:
            print("\n" + "-"*125)
            print(f"{'VERTEX_ID':<12} | {'SHARING L2 PARCELS':<18} | {'(X,Y) FROM L2 (ADJUSTED)':<32} | {'(X,Y) FROM TARGET FIXED':<32} | {'WEIGHT'}")
            print("-"*125)

        # Loop over unique vertex points from L2 adjusted layer
        for idx, pt_row in gdf_adj_vertices.iterrows():
            v_id = str(pt_row["vertex_id"]).strip()
            l2_x = float(pt_row["geometry"].x)
            l2_y = float(pt_row["geometry"].y)
            l2_coord = (l2_x, l2_y)

            # =========================================================================
            # FIXED: EXACT TEXT ELEMENT MATCHING INSIDE SPLIT LIST
            # =========================================================================
            sharing_l2_parcels = []
            for _, p_row in self.gdf_all[self.gdf_all['Class'] == 'L2'].iterrows():
                p_labels = [lbl.strip() for lbl in str(p_row[self.vertex_col]).split(",") if lbl.strip()]
                if v_id in p_labels:
                    sharing_l2_parcels.append(p_row)

            # If NO adjustable L2 parcels actually own this vertex, skip it!
            if not sharing_l2_parcels:
                continue

            p_id_list = ", ".join([f"P{int(p['id'])}" for p in sharing_l2_parcels])
            l2_str = f"({l2_x:.4f}, {l2_y:.4f})"

            # =========================================================================
            # HIERARCHICAL MATCHING ENGINE RULES
            # =========================================================================
            
            # PRIORITY 1: Check for identical vertex ID inside the L1 fixed framework
            if v_id in l1_targets:
                target_coord = l1_targets[v_id]
                self.control_targets[v_id] = target_coord
                target_str = f"({target_coord[0]:.4f}, {target_coord[1]:.4f})"
                
                for _ in range(len(sharing_l2_parcels)):
                    src_pts.append(l2_coord)
                    dst_pts.append(target_coord)
                    weights.append(1.0)  # Standard baseline constraint
                    
                if self.show_pairs:
                    print(f"{v_id:<12} | {p_id_list:<18} | {l2_str:<32} | {target_str:<32} | {1.0:<6} [L1 MATCH]")

            # PRIORITY 2: Fallback to fix_control layer anchor mark only if no L1 match exists
            elif v_id in fix_lookup:
                target_coord = fix_lookup[v_id]
                self.control_targets[v_id] = target_coord
                target_str = f"({target_coord[0]:.4f}, {target_coord[1]:.4f})"
                
                for _ in range(len(sharing_l2_parcels)):
                    src_pts.append(l2_coord)
                    dst_pts.append(target_coord)
                    weights.append(self.fix_control_weight)  # Higher custom constraint weight
                
                if self.show_pairs:
                    print(f"{v_id:<12} | {p_id_list:<18} | {l2_str:<32} | {target_str:<32} | {self.fix_control_weight:<6} [FIX_CONTROL]")

        if self.show_pairs:
            print("-"*125 + "\n")

        # 4. Global Transformation Least-Squares Execution
        if len(src_pts) < 3:
            print(f"[SAFE MODE] Only {len(src_pts)} text-matched pairs found (minimum 3 required). Skipping warp matrix operation.")
        else:
            print(f"[COMPUTE] Fitting Weighted Affine Regression matrix over {len(src_pts)} observation vectors...")
            X = np.hstack([np.array(src_pts), np.ones((len(src_pts), 1))])
            Y = np.array(dst_pts)
            W = np.diag(weights)
            
            # WLS Formula: (X^T * W * X)^-1 * X^T * W * Y
            Xt_W = np.dot(X.T, W)
            affine_matrix = np.linalg.solve(np.dot(Xt_W, X), np.dot(Xt_W, Y))
            print("[COMPUTE] Global Weighted Affine matrix computed successfully.")

            # Transform all parcel features uniformly down the line
            warped_geometries = []
            for idx, row in self.gdf_all.iterrows():
                coords = np.array(row["geometry"].exterior.coords)
                padded_coords = np.hstack([coords, np.ones((len(coords), 1))])
                warped_geometries.append(Polygon(np.dot(padded_coords, affine_matrix)))
            self.gdf_all["geometry"] = warped_geometries
            print("[COMPUTE] Layout fabric configurations warped successfully.")

        # 5. Data Layer Exports and Disk IO
        if os.path.exists(self.output_gpkg): 
            os.remove(self.output_gpkg)
            
        print(f"[EXPORT] Writing layer 'global_aligned' into database: {self.output_gpkg}")
        self.gdf_all.to_file(self.output_gpkg, layer="global_aligned", driver="GPKG")
        if self.gdf_fix is not None:
            print(f"[EXPORT] Writing layer 'fix_control' into database: {self.output_gpkg}")
            self.gdf_fix.to_file(self.output_gpkg, layer="fix_control", driver="GPKG")

        img_base_path = os.path.abspath(os.path.join(self.result_dir, "03_conflation_result"))
        print(f"[EXPORT] Rendering high-resolution inspection map: {img_base_path}.png")
        print(f"[EXPORT] Rendering lossless vector workspace sheet: {img_base_path}.svg")
        
        PlotMap.render_map(
            layers={"Warped Fabric Output": self.gdf_all}, 
            title="Global Weighted Affine Fabric Warp Framework", 
            filename_base=img_base_path, 
            targets=self.control_targets
        )
        print(f"[STAGE 3 COMPLETED] Workspace database exported cleanly to {self.output_gpkg}\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-w", "--weight", type=float, default=10000.0)
    parser.add_argument("-p", "--pair", action="store_true")
    args = parser.parse_args()

    PiecewiseControlWarpPipeline(
        weight=args.weight, 
        show_pairs=args.pair
    ).run_transform_pipeline()
